vich_uploader:
    db_driver: orm

    mappings:
       kimora:
           uri_prefix: /images/kimora
           upload_destination: '%kernel.project_dir%/public/images/kimora'

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
 